name: Test multi file workflows

on:
  push:
    branches:
      - main
      - develop

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Hello, world!"