name: Run Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install flake8
      run: |
        pip install flake8

    - name: Run flake8 linter
      run: |
        flake8 .

    - name: Run tests
      run: |
        python manage.py test